/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.1.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the application plugin to add support for building a CLI application in Java.
    application

//    id("io.github.cosmicsilence.scalafix").version("0.1.11")

}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

var http4sVersion = "0.21.26"

//tasks.named("run") {
//    dependsOn("compileScala")
//}

tasks.withType<ScalaCompile>().configureEach {
    this.scalaCompileOptions.forkOptions.apply {
//        memoryMaximumSize = "1g"

        options.compilerArgs.add("-Ytasty-reader")
    }
}

var scalaBinaryVersion = "2.13"

dependencies {
    // Use Scala 2.13 in our library project
    implementation("org.scala-lang:scala-library:2.13.5")
    scalaCompilerPlugins("org.typelevel:kind-projector_${scalaBinaryVersion}.1:0.11.0")

    implementation("org.typelevel:cats-effect_${scalaBinaryVersion}:3.2.2")
    implementation("org.typelevel:cats-core_${scalaBinaryVersion}:2.6.1")
    
    implementation("org.http4s:http4s-dsl_${scalaBinaryVersion}:${http4sVersion}")
    implementation("org.http4s:http4s-blaze-server_${scalaBinaryVersion}:${http4sVersion}")
    implementation("org.http4s:http4s-blaze-client_${scalaBinaryVersion}:${http4sVersion}")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1-jre")

    // Use Scalatest for testing our library
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.scalatest:scalatest_${scalaBinaryVersion}:3.2.6")
    testImplementation("org.scalatestplus:junit-4-13_${scalaBinaryVersion}:3.2.2.0")

    // Need scala-xml at test runtime
    testRuntimeOnly("org.scala-lang.modules:scala-xml_${scalaBinaryVersion}:1.2.0")
}

application {
    // Define the main class for the application.
    mainClass.set("memetiq.Main")
}
